mfd: simple-mfd-i2c: Select MFD_CORE to fix build error
MFD_SIMPLE_MFD_I2C should select the MFD_CORE to a prevent build error:

aarch64-linux-ld: drivers/mfd/simple-mfd-i2c.o: in function `simple_mfd_i2c_probe':
drivers/mfd/simple-mfd-i2c.c:55: undefined reference to `devm_mfd_add_devices'

Fixes: 3abee4579484 ("mfd: Add simple regmap based I2C driver")
Signed-off-by: Robert Marko <robert.marko@sartura.hr>