iommu/arm-smmu-v3: add missing header
str_read_write is currently undeclared and thus compilation will fail with:
drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c:1911:25: error: implicit declaration of function ‘str_read_write’; did you mean ‘sb_end_write’? [-Wimplicit-function-declaration]

So include the missing linux/string_choices.h header to fix compilation.

Fixes: f2c77f6e41e6 ("iommu/arm-smmu-v3: Use str_read_write helper w/ logs")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202501111926.qOpnlK9J-lkp@intel.com/
Signed-off-by: Robert Marko <robert.marko@sartura.hr>